/*
 * This source file was generated by the Gradle 'init' task
 */
package game;

import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.system.MemoryUtil.*;

public class App {
    private long window;

    public void run() {
        init();
        loop();
        cleanup();
    }

    private void init() {
        System.out.println("Inzializazzione di tutto...");
        if (!glfwInit()) {
            throw new RuntimeException("Errore nel lancio della finestra!");
        }

        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
        glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
        

        window = glfwCreateWindow(800, 600, "Mincroft", NULL, NULL);

        if (window == NULL) {
            throw new RuntimeException("Errore nel lancio della finestra!");
        }

        glfwMakeContextCurrent(window);
        glfwSwapInterval(1);

        glfwShowWindow(window);
    }

    private void loop() {
        System.out.println("Entrato nel game loop!");
        
        org.lwjgl.opengl.GL.createCapabilities();
        org.lwjgl.opengl.GL11.glClearColor(0.5f, 0.8f, 1.0f, 0.0f); // Cielo azzurro
        
        while (!glfwWindowShouldClose(window)) {
            // Pulisce lo schermo
            org.lwjgl.opengl.GL11.glClear(
                org.lwjgl.opengl.GL11.GL_COLOR_BUFFER_BIT | org.lwjgl.opengl.GL11.GL_DEPTH_BUFFER_BIT
            );
            
            // --- INIZIO: DISEGNO IL NOSTRO PRIMO BLOCCO (ERBA) ---
            
            // 1. Scegliamo il colore: RGB (Rosso, Verde, Blu) da 0.0 a 1.0
            org.lwjgl.opengl.GL11.glColor3f(0.2f, 0.8f, 0.2f); // Questo è un bel Verde
            
            // 2. Diciamo a OpenGL che stiamo per disegnare un Quadrato (Quads)
            org.lwjgl.opengl.GL11.glBegin(org.lwjgl.opengl.GL11.GL_QUADS); 
            
                // 3. Coordinate dei 4 angoli (X, Y)
                // In OpenGL il centro dello schermo è X=0, Y=0. 
                // Il massimo in alto/destra è 1.0, il massimo in basso/sinistra è -1.0.
                org.lwjgl.opengl.GL11.glVertex2f(-0.5f,  0.5f); // Angolo in Alto a Sinistra
                org.lwjgl.opengl.GL11.glVertex2f( 0.5f,  0.5f); // Angolo in Alto a Destra
                org.lwjgl.opengl.GL11.glVertex2f( 0.5f, -0.5f); // Angolo in Basso a Destra
                org.lwjgl.opengl.GL11.glVertex2f(-0.5f, -0.5f); // Angolo in Basso a Sinistra
                
            // 4. Fine del disegno del blocco
            org.lwjgl.opengl.GL11.glEnd(); 
            
            // --- FINE DISEGNO ---

            // QUESTE DUE RIGHE DEVONO STARE DENTRO IL CICLO WHILE!
            glfwSwapBuffers(window);
            glfwPollEvents();
        }
    }

    private void cleanup() {
        System.out.println("Pulizia della memoria!");
        glfwDestroyWindow(window);
        glfwTerminate();
    }

    public static void main(String[] args) {
        new App().run();
    }
}
