/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Core */

#ifndef _Included_Core
#define _Included_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Core
 * Method:    somma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Core_somma
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Core
 * Method:    moltiplica
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Core_moltiplica
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Core
 * Method:    dividi
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_Core_dividi
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
